.\" Man page for desktopserver
.TH DESKTOPSERVER 1 "17 September 2019" "UKUI Desktop Environment"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME"
desktopserver \- The tool for the UKUI Desktop Environment
.SH "SYNOPSIS"
.B desktopserver
.SH "DESCRIPTION"
The \fBdesktopserver\fR program is a part of the ukui-interface, It is personalization service process started based on d-bus.
.PP
This manual page documents the \fBdesktopserver\fR command.
.P
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
https://github.com/ukui/ukui-interface/issues
.SH "AUTHORS"
.SS This Man Page has been written for the UKUI Desktop Environment by:
liuhao <liuhao@kylinos.cn> (2019)
.SH "SEE ALSO"
